name: Example Workflow

# test for https://github.com/ocaml/setup-ocaml/issues/866#issuecomment-2702110831

on: [push, pull_request]

jobs:
  buildv3:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-latest' , 'ubuntu-latest' ]


    runs-on: ${{ matrix.os }}
    name: build-${{ matrix.os }}-v3
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 4.13.1
    - run: opam config report
    - run: opam exec -- bash -c 'install -d foo/'


  buildv3216:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-latest' , 'ubuntu-latest' ]


    runs-on: ${{ matrix.os }}
    name: build-${{ matrix.os }}-v3216
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: ocaml/setup-ocaml@v3.2.16
      with:
        ocaml-compiler: 4.13.1
    - run: opam config report
    - run: opam exec -- bash -c 'install -d foo/'

