name: Example Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - container: 'node:12'
          - container: ''

    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: Run a command
        run: |
          if [ '${{ matrix.use_container }}' = true ]; then
            echo "Running in a container"
          else
            echo "Running in the runner environment"
          fi

      
