name: Example Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: support perf
      run: |
        sudo sh -c 'echo 0 >/proc/sys/kernel/perf_event_paranoid'
        sudo sh -c 'echo 0 >/proc/sys/kernel/kptr_restrict'
    - run: perf stat ls
