name: Example Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - use_container: true
            container_image: 'node:12'
          - use_container: false

    container:
      image: ${{ matrix.use_container && matrix.container_image }}

    steps:
      - uses: actions/checkout@v2
      - name: Run a command
        run: |
          if [ '${{ matrix.use_container }}' = true ]; then
            echo "Running in a container"
          else
            echo "Running in the runner environment"
          fi

      
