name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up OCaml
        uses: avsm/setup-ocaml@v1.1.10
        with:
          ocaml-version: 4.11.1
      - run: opam list
        if: always()
      - run: opam list
        shell: bash
        if: always()
      - run: opam list
        shell: cmd
        if: always()
      - run: C:\tools\cygwin\bin\bash.exe -l -c 'cd "%cd%"; opam list'
        shell: cmd
        if: always()
      - run: |
          %CYGWIN_ROOT%\bin\bash.exe -l -c 'cd "%cd%"; opam list'
        shell: cmd
        if: always()
