name: Example Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: coqorg/coq:dev
    steps:
      - run: |
          id -u
          id -g
          ls -la .
          for d in /__w /github/workflow; do
            sudo chmod -R a=u $d
          done
      - uses: actions/checkout@v4
