name: Example Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: support perf
      run: |
        sudo sh -c 'echo 0 >/proc/sys/kernel/perf_event_paranoid'
        sudo sh -c 'echo 0 >/proc/sys/kernel/kptr_restrict'
    - run: perf stat ls
    - name: Install perf
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-tools-common linux-tools-$(uname -r)

      - name: List perf events
        run: |
          perf list

      - name: Run perf stat
        run: |
          sudo perf stat -e instructions,cycles -- sleep 1
