name: Example Workflow

# test for https://github.com/ocaml/setup-ocaml/issues/866#issuecomment-2702110831

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ocaml_version: [ 'v3' , 'v3.2.16' ]


    runs-on: windows-latest
    name: build
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: ocaml/setup-ocaml@${{ matrix.ocaml_version }}
      with:
        ocaml-compiler: 4.13.1
    - run: opam config report
    - run: opam exec -- bash -c 'install -d foo/'


