name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-wasm-of-ocaml:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        coq-version: [ 'master' ]
        ocaml-compiler: [ '4.14.1' ]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
    - name: set up custom dune and wasm_of_ocaml
      run: |
        eval $(opam env)
        opam update -y
        opam pin add -y 'https://github.com/ocaml-wasm/dune.git#wasm'
        opam pin add -y --no-action https://github.com/ocaml-wasm/wasm_of_ocaml.git
    - name: install js_of_ocaml
      run: |
        eval $(opam env)
        opam install -y --best-effort js_of_ocaml
        opam install -y js_of_ocaml
    - name: install wasm_of_ocaml
      run: |
        eval $(opam env)
        opam install -y --best-effort wasm_of_ocaml-compiler
        opam install -y wasm_of_ocaml-compiler
      if: always()
