name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: macOS-10.15

    steps:
    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.11.1
    - run: opam env
    - uses: actions/checkout@v2
      with:
        clean: false
    - run: opam env
