name: Example Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    #container: coqorg/coq:dev
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - run: sudo chmod -R a+rw .
    - name: echo
      uses: coq-community/docker-coq-action@v1
      with:
        coq_version: dev
        ocaml_version: default
        export: CI ALLOW_DIFF COQCHKEXTRAFLAGS GITHUB_STEP_SUMMARY COQ_IMAGE
        custom_script: |
          echo "${COQ_IMAGE}"
          printf "COQ_IMAGE=%s\n" "${COQ_IMAGE}" >> .coqimage
    - run: docker images --format "{{.Repository}}:{{.Tag}}" | grep -o 'coqorg/coq:.*dev.*'
    - run: cat .coqimage >> ${GITHUB_ENV}
    - run: echo "${COQ_IMAGE}"
