name: Example Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: coqorg/coq:dev
    steps:
      - run: |
          id -u
          id -g
      - run: |
          id -u
          id -g
        container: ''
      - uses: actions/checkout@v4
